# Generated by Django 2.1.4 on 2019-02-15 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('tooltip', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('cover', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('quote', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('SP', 'Sponsor'), ('ME', 'Member'), ('PO', 'Poster'), ('MO', 'Moderator'), ('AD', 'Administrator')], default='MB', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('vi_sub', models.CharField(max_length=255)),
                ('en_sub', models.CharField(max_length=255)),
                ('vi_transcript', models.TextField(blank=True)),
                ('en_transcript', models.TextField(blank=True)),
                ('view_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_created_by', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_published_by', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Source')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sponsor_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Category')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Speaker')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.SubCategory')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Video')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Video'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_core_app.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='videosubcategory',
            unique_together={('video', 'subcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='videospeaker',
            unique_together={('video', 'speaker')},
        ),
        migrations.AlterUniqueTogether(
            name='videocategory',
            unique_together={('video', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('slug', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='playlistvideo',
            unique_together={('playlist', 'video')},
        ),
    ]
